import type { GEO_ISO2 } from '@/modules/geo/types';

export const ISO2_RU_MAP: Record<string, GEO_ISO2> = {
  'Афганистан': 'AF',
  'Аландские острова': 'AX',
  'Албания': 'AL',
  'Алжир': 'DZ',
  'Американское Самоа': 'AS',
  'Андорра': 'AD',
  'Ангола': 'AO',
  'Ангилья': 'AI',
  'Антарктида': 'AQ',
  'Антигуа и Барбуда': 'AG',
  'Аргентина': 'AR',
  'Армения': 'AM',
  'Аруба': 'AW',
  'Австралия': 'AU',
  'Австрия': 'AT',
  'Азербайджан': 'AZ',
  'Багамские Острова': 'BS',
  'Бахрейн': 'BH',
  'Бангладеш': 'BD',
  'Барбадос': 'BB',
  'Беларусь': 'BY',
  'Бельгия': 'BE',
  'Белиз': 'BZ',
  'Бенин': 'BJ',
  'Бермудские острова': 'BM',
  'Бутан': 'BT',
  'Боливия': 'BO',
  'Босния и Герцеговина': 'BA',
  'Ботсвана': 'BW',
  'Остров Буве': 'BV',
  'Бразилия': 'BR',
  'Британская территория в Индийском океане': 'IO',
  'Бруней-Даруссалам': 'BN',
  'Болгария': 'BG',
  'Буркина-Фасо': 'BF',
  'Бурунди': 'BI',
  'Камбоджа': 'KH',
  'Камерун': 'CM',
  'Канада': 'CA',
  'Кабо-Верде': 'CV',
  'Каймановы острова': 'KY',
  'Центральноафриканская Республика': 'CF',
  'Чад': 'TD',
  'Чили': 'CL',
  'Китай': 'CN',
  'Остров Рождества': 'CX',
  'Кокосовые острова (Килинг)': 'CC',
  'Колумбия': 'CO',
  'Коморские острова': 'KM',
  'Конго': 'CG',
  'Конго, Демократическая Республика': 'CD',
  'Острова Кука': 'CK',
  'Коста-Рика': 'CR',
  'Берег Слоновой Кости': 'CI',
  'Хорватия': 'HR',
  'Куба': 'CU',
  'Кипр': 'CY',
  'Чешская Республика': 'CZ',
  'Дания': 'DK',
  'Джибути': 'DJ',
  'Доминика': 'DM',
  'Доминиканская Республика': 'DO',
  'Эквадор': 'EC',
  'Египет': 'EG',
  'Сальвадор': 'SV',
  'Экваториальная Гвинея': 'GQ',
  'Эритрея': 'ER',
  'Эстония': 'EE',
  'Эфиопия': 'ET',
  'Фолклендские (Мальвинские) острова': 'FK',
  'Фарерские острова': 'FO',
  'Фиджи': 'FJ',
  'Финляндия': 'FI',
  'Франция': 'FR',
  'Французская Гвиана': 'GF',
  'Французская Полинезия': 'PF',
  'Французские Южные территории': 'TF',
  'Габон': 'GA',
  'Гамбия': 'GM',
  'Грузия': 'GE',
  'Германия': 'DE',
  'Гана': 'GH',
  'Гибралтар': 'GI',
  'Греция': 'GR',
  'Гренландия': 'GL',
  'Гренада': 'GD',
  'Гваделупа': 'GP',
  'Гуам': 'GU',
  'Гватемала': 'GT',
  'Гернси': 'GG',
  'Гвинея': 'GN',
  'Гвинея-Бисау': 'GW',
  'Гайана': 'GY',
  'Гаити': 'HT',
  'Остров Херд и острова Макдональд': 'HM',
  'Святой Престол (город-государство Ватикан)': 'VA',
  'Гондурас': 'HN',
  'Гонконг': 'HK',
  'Венгрия': 'HU',
  'Исландия': 'IS',
  'Индия': 'IN',
  'Индонезия': 'ID',
  'Иран, Исламская Республика': 'IR',
  'Ирак': 'IQ',
  'Ирландия': 'IE',
  'Остров Мэн': 'IM',
  'Израиль': 'IL',
  'Италия': 'IT',
  'Ямайка': 'JM',
  'Япония': 'JP',
  'Джерси': 'JE',
  'Иордания': 'JO',
  'Казахстан': 'KZ',
  'Кения': 'KE',
  'Кирибати': 'KI',
  'Корея': 'KR',
  'Северная Корея': 'KP',
  'Кувейт': 'KW',
  'Кыргызстан': 'KG',
  'Лаосская Народно-Демократическая Республика': 'LA',
  'Латвия': 'LV',
  'Ливан': 'LB',
  'Лесото': 'LS',
  'Либерия': 'LR',
  'Ливийская Арабская Джамахирия': 'LY',
  'Лихтенштейн': 'LI',
  'Литва': 'LT',
  'Люксембург': 'LU',
  'Макао': 'MO',
  'Македония': 'MK',
  'Мадагаскар': 'MG',
  'Малави': 'MW',
  'Малайзия': 'MY',
  'Мальдивы': 'MV',
  'Мали': 'ML',
  'Мальта': 'MT',
  'Маршалловы острова': 'MH',
  'Мартиника': 'MQ',
  'Мавритания': 'MR',
  'Маврикий': 'MU',
  'Майотта': 'YT',
  'Мексика': 'MX',
  'Микронезия (Федеративные Штаты)': 'FM',
  'Молдова': 'MD',
  'Монако': 'MC',
  'Монголия': 'MN',
  'Черногория': 'ME',
  'Монтсеррат': 'MS',
  'Марокко': 'MA',
  'Мозамбик': 'MZ',
  'Мьянма': 'MM',
  'Намибия': 'NA',
  'Науру': 'NR',
  'Непал': 'NP',
  'Нидерланды': 'NL',
  'Нидерландские Антильские острова': 'AN',
  'Новая Каледония': 'NC',
  'Новая Зеландия': 'NZ',
  'Никарагуа': 'NI',
  'Нигер': 'NE',
  'Нигерия': 'NG',
  'Ниуэ': 'NU',
  'Остров Норфолк': 'NF',
  'Северные Марианские острова': 'MP',
  'Норвегия': 'NO',
  'Оман': 'OM',
  'Пакистан': 'PK',
  'Палау': 'PW',
  'Палестинская территория (оккупированная)': 'PS',
  'Панама': 'PA',
  'Папуа — Новая Гвинея': 'PG',
  'Парагвай': 'PY',
  'Перу': 'PE',
  'Филиппины': 'PH',
  'Питкэрн': 'PN',
  'Польша': 'PL',
  'Португалия': 'PT',
  'Пуэрто-Рико': 'PR',
  'Катар': 'QA',
  'Реюньон': 'RE',
  'Румыния': 'RO',
  'Российская Федерация': 'RU',
  'Руанда': 'RW',
  'Сен-Бартелеми': 'BL',
  'Остров Святой Елены': 'SH',
  'Сент-Китс и Невис': 'KN',
  'Сент-Люсия': 'LC',
  'Сен-Мартен': 'MF',
  'Сен-Пьер и Микелон': 'PM',
  'Сент-Винсент и Гренадины': 'VC',
  'Самоа': 'WS',
  'Сан-Марино': 'SM',
  'Сан-Томе и Принсипи': 'ST',
  'Саудовская Аравия': 'SA',
  'Сенегал': 'SN',
  'Сербия': 'RS',
  'Сейшельские Острова': 'SC',
  'Сьерра-Леоне': 'SL',
  'Сингапур': 'SG',
  'Словакия': 'SK',
  'Словения': 'SI',
  'Соломоновы Острова': 'SB',
  'Сомали': 'SO',
  'Южная Африка': 'ZA',
  'Южная Георгия и Сандвичевы Острова': 'GS',
  'Испания': 'ES',
  'Шри-Ланка': 'LK',
  'Судан': 'SD',
  'Суринам': 'SR',
  'Шпицберген и Ян-Майен': 'SJ',
  'Свазиленд': 'SZ',
  'Швеция': 'SE',
  'Швейцария': 'CH',
  'Сирийская Арабская Республика': 'SY',
  'Тайвань': 'TW',
  'Таджикистан': 'TJ',
  'Танзания': 'TZ',
  'Таиланд': 'TH',
  'Тимор-Лешти': 'TL',
  'Того': 'TG',
  'Токелау': 'TK',
  'Тонга': 'TO',
  'Тринидад и Тобаго': 'TT',
  'Тунис': 'TN',
  'Турция': 'TR',
  'Туркменистан': 'TM',
  'Острова Тёркс и Кайкос': 'TC',
  'Тувалу': 'TV',
  'Уганда': 'UG',
  'Украина': 'UA',
  'Объединенные Арабские Эмираты': 'AE',
  'Великобритания': 'GB',
  'Соединенные Штаты': 'US',
  'Отдаленные острова США': 'UM',
  'Уругвай': 'UY',
  'Узбекистан': 'UZ',
  'Вануату': 'VU',
  'Венесуэла': 'VE',
  'Вьетнам': 'VN',
  'Виргинские острова, Британская': 'VG',
  'Виргинские острова, США': 'VI',
  'Уоллис и Футуна': 'WF',
  'Западная Сахара': 'EH',
  'Йемен': 'YE',
  'Замбия': 'ZM',
  'Зимбабве': 'ZW',
};

export const ISO2_EN_MAP: Record<string, GEO_ISO2> = {
  'Afghanistan': 'AF',
  'Aland Islands': 'AX',
  'Albania': 'AL',
  'Algeria': 'DZ',
  'American Samoa': 'AS',
  'Andorra': 'AD',
  'Angola': 'AO',
  'Anguilla': 'AI',
  'Antarctica': 'AQ',
  'Antigua And Barbuda': 'AG',
  'Argentina': 'AR',
  'Armenia': 'AM',
  'Aruba': 'AW',
  'Australia': 'AU',
  'Austria': 'AT',
  'Azerbaijan': 'AZ',
  'Bahamas': 'BS',
  'Bahrain': 'BH',
  'Bangladesh': 'BD',
  'Barbados': 'BB',
  'Belarus': 'BY',
  'Belgium': 'BE',
  'Belize': 'BZ',
  'Benin': 'BJ',
  'Bermuda': 'BM',
  'Bhutan': 'BT',
  'Bolivia': 'BO',
  'Bosnia And Herzegovina': 'BA',
  'Botswana': 'BW',
  'Bouvet Island': 'BV',
  'Brazil': 'BR',
  'British Indian Ocean Territory': 'IO',
  'Brunei Darussalam': 'BN',
  'Bulgaria': 'BG',
  'Burkina Faso': 'BF',
  'Burundi': 'BI',
  'Cambodia': 'KH',
  'Cameroon': 'CM',
  'Canada': 'CA',
  'Cape Verde': 'CV',
  'Cayman Islands': 'KY',
  'Central African Republic': 'CF',
  'Chad': 'TD',
  'Chile': 'CL',
  'China': 'CN',
  'Christmas Island': 'CX',
  'Cocos (Keeling) Islands': 'CC',
  'Colombia': 'CO',
  'Comoros': 'KM',
  'Congo': 'CG',
  'Congo, Democratic Republic': 'CD',
  'Cook Islands': 'CK',
  'Costa Rica': 'CR',
  'Cote D"Ivoire': 'CI',
  'Croatia': 'HR',
  'Cuba': 'CU',
  'Cyprus': 'CY',
  'Czech Republic': 'CZ',
  'Denmark': 'DK',
  'Djibouti': 'DJ',
  'Dominica': 'DM',
  'Dominican Republic': 'DO',
  'Ecuador': 'EC',
  'Egypt': 'EG',
  'El Salvador': 'SV',
  'Equatorial Guinea': 'GQ',
  'Eritrea': 'ER',
  'Estonia': 'EE',
  'Ethiopia': 'ET',
  'Falkland Islands (Malvinas)': 'FK',
  'Faroe Islands': 'FO',
  'Fiji': 'FJ',
  'Finland': 'FI',
  'France': 'FR',
  'French Guiana': 'GF',
  'French Polynesia': 'PF',
  'French Southern Territories': 'TF',
  'Gabon': 'GA',
  'Gambia': 'GM',
  'Georgia': 'GE',
  'Germany': 'DE',
  'Ghana': 'GH',
  'Gibraltar': 'GI',
  'Greece': 'GR',
  'Greenland': 'GL',
  'Grenada': 'GD',
  'Guadeloupe': 'GP',
  'Guam': 'GU',
  'Guatemala': 'GT',
  'Guernsey': 'GG',
  'Guinea': 'GN',
  'Guinea-Bissau': 'GW',
  'Guyana': 'GY',
  'Haiti': 'HT',
  'Heard Island & Mcdonald Islands': 'HM',
  'Holy See (Vatican City State)': 'VA',
  'Honduras': 'HN',
  'Hong Kong': 'HK',
  'Hungary': 'HU',
  'Iceland': 'IS',
  'India': 'IN',
  'Indonesia': 'ID',
  'Iran, Islamic Republic Of': 'IR',
  'Iraq': 'IQ',
  'Ireland': 'IE',
  'Isle Of Man': 'IM',
  'Israel': 'IL',
  'Italy': 'IT',
  'Jamaica': 'JM',
  'Japan': 'JP',
  'Jersey': 'JE',
  'Jordan': 'JO',
  'Kazakhstan': 'KZ',
  'Kenya': 'KE',
  'Kiribati': 'KI',
  'Korea': 'KR',
  'North Korea': 'KP',
  'Kuwait': 'KW',
  'Kyrgyzstan': 'KG',
  'Lao People"s Democratic Republic': 'LA',
  'Latvia': 'LV',
  'Lebanon': 'LB',
  'Lesotho': 'LS',
  'Liberia': 'LR',
  'Libyan Arab Jamahiriya': 'LY',
  'Liechtenstein': 'LI',
  'Lithuania': 'LT',
  'Luxembourg': 'LU',
  'Macao': 'MO',
  'Macedonia': 'MK',
  'Madagascar': 'MG',
  'Malawi': 'MW',
  'Malaysia': 'MY',
  'Maldives': 'MV',
  'Mali': 'ML',
  'Malta': 'MT',
  'Marshall Islands': 'MH',
  'Martinique': 'MQ',
  'Mauritania': 'MR',
  'Mauritius': 'MU',
  'Mayotte': 'YT',
  'Mexico': 'MX',
  'Micronesia, Federated States Of': 'FM',
  'Moldova': 'MD',
  'Monaco': 'MC',
  'Mongolia': 'MN',
  'Montenegro': 'ME',
  'Montserrat': 'MS',
  'Morocco': 'MA',
  'Mozambique': 'MZ',
  'Myanmar': 'MM',
  'Namibia': 'NA',
  'Nauru': 'NR',
  'Nepal': 'NP',
  'Netherlands': 'NL',
  'Netherlands Antilles': 'AN',
  'New Caledonia': 'NC',
  'New Zealand': 'NZ',
  'Nicaragua': 'NI',
  'Niger': 'NE',
  'Nigeria': 'NG',
  'Niue': 'NU',
  'Norfolk Island': 'NF',
  'Northern Mariana Islands': 'MP',
  'Norway': 'NO',
  'Oman': 'OM',
  'Pakistan': 'PK',
  'Palau': 'PW',
  'Palestinian Territory, Occupied': 'PS',
  'Panama': 'PA',
  'Papua New Guinea': 'PG',
  'Paraguay': 'PY',
  'Peru': 'PE',
  'Philippines': 'PH',
  'Pitcairn': 'PN',
  'Poland': 'PL',
  'Portugal': 'PT',
  'Puerto Rico': 'PR',
  'Qatar': 'QA',
  'Reunion': 'RE',
  'Romania': 'RO',
  'Russian Federation': 'RU',
  'Rwanda': 'RW',
  'Saint Barthelemy': 'BL',
  'Saint Helena': 'SH',
  'Saint Kitts And Nevis': 'KN',
  'Saint Lucia': 'LC',
  'Saint Martin': 'MF',
  'Saint Pierre And Miquelon': 'PM',
  'Saint Vincent And Grenadines': 'VC',
  'Samoa': 'WS',
  'San Marino': 'SM',
  'Sao Tome And Principe': 'ST',
  'Saudi Arabia': 'SA',
  'Senegal': 'SN',
  'Serbia': 'RS',
  'Seychelles': 'SC',
  'Sierra Leone': 'SL',
  'Singapore': 'SG',
  'Slovakia': 'SK',
  'Slovenia': 'SI',
  'Solomon Islands': 'SB',
  'Somalia': 'SO',
  'South Africa': 'ZA',
  'South Georgia And Sandwich Isl.': 'GS',
  'Spain': 'ES',
  'Sri Lanka': 'LK',
  'Sudan': 'SD',
  'Suriname': 'SR',
  'Svalbard And Jan Mayen': 'SJ',
  'Swaziland': 'SZ',
  'Sweden': 'SE',
  'Switzerland': 'CH',
  'Syrian Arab Republic': 'SY',
  'Taiwan': 'TW',
  'Tajikistan': 'TJ',
  'Tanzania': 'TZ',
  'Thailand': 'TH',
  'Timor-Leste': 'TL',
  'Togo': 'TG',
  'Tokelau': 'TK',
  'Tonga': 'TO',
  'Trinidad And Tobago': 'TT',
  'Tunisia': 'TN',
  'Turkey': 'TR',
  'Turkmenistan': 'TM',
  'Turks And Caicos Islands': 'TC',
  'Tuvalu': 'TV',
  'Uganda': 'UG',
  'Ukraine': 'UA',
  'United Arab Emirates': 'AE',
  'United Kingdom': 'GB',
  'United States': 'US',
  'United States Outlying Islands': 'UM',
  'Uruguay': 'UY',
  'Uzbekistan': 'UZ',
  'Vanuatu': 'VU',
  'Venezuela': 'VE',
  'Vietnam': 'VN',
  'Virgin Islands, British': 'VG',
  'Virgin Islands, U.S.': 'VI',
  'Wallis And Futuna': 'WF',
  'Western Sahara': 'EH',
  'Yemen': 'YE',
  'Zambia': 'ZM',
  'Zimbabwe': 'ZW',
};
